/* Database schema to keep the structure of entire database. */
-- Create Database
CREATE DATABASE vet_clinic;

-- Create table
CREATE TABLE animals (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth DATE NOT NULL,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL
);

-- Add species column of type string to animals table
ALTER TABLE animals
ADD species VARCHAR;