/* Database schema to keep the structure of entire database. */
-- Create Database
CREATE DATABASE vet_clinic;

-- Create table
CREATE TABLE animals (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth DATE NOT NULL,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL
);

-- Add species column of type string to animals table
ALTER TABLE animals
ADD species VARCHAR;

-- Create owners table
CREATE TABLE owners (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR,
    age INT
);

-- Create species table
CREATE TABLE species (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR
);

-- Modify animals table (Remove species column)
ALTER TABLE animals
DROP species;

-- Modify animals table (Add species_id column)
ALTER TABLE animals
ADD species_id INT,
ADD CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(id);

-- Modify animals table (Add owner_id column)
ALTER TABLE animals
ADD owner_id INT,
ADD CONSTRAINT fk_owner FOREIGN KEY(owner_id) REFERENCES owners(id);
